[package]
name = "rust-firestore-snapshot-core"
version = "0.1.0"
edition = "2018"

[dependencies]
firestore_grpc = "0.95.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-recursion = "1.0.0"
prost-types = "0.9.0"
