#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    non_snake_case
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

use crate::api::*;
use flutter_rust_bridge::*;

// Section: wire functions

#[no_mangle]
pub extern "C" fn wire_get_collection(
    port_: i64,
    project_id: *mut wire_uint_8_list,
    token: *mut wire_uint_8_list,
    collection_path: *mut wire_uint_8_list,
    output_path: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_collection",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_project_id = project_id.wire2api();
            let api_token = token.wire2api();
            let api_collection_path = collection_path.wire2api();
            let api_output_path = output_path.wire2api();
            move |task_callback| {
                get_collection(
                    api_project_id,
                    api_token,
                    api_collection_path,
                    api_output_path,
                )
            }
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_update_collection(
    port_: i64,
    project_id: *mut wire_uint_8_list,
    token: *mut wire_uint_8_list,
    collection_path: *mut wire_uint_8_list,
    input_file_path: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "update_collection",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_project_id = project_id.wire2api();
            let api_token = token.wire2api();
            let api_collection_path = collection_path.wire2api();
            let api_input_file_path = input_file_path.wire2api();
            move |task_callback| {
                update_collection(
                    api_project_id,
                    api_token,
                    api_collection_path,
                    api_input_file_path,
                )
            }
        },
    )
}

// Section: wire structs

#[repr(C)]
#[derive(Clone)]
pub struct wire_uint_8_list {
    ptr: *mut u8,
    len: i32,
}

// Section: wire enums

// Section: allocate functions

#[no_mangle]
pub extern "C" fn new_uint_8_list(len: i32) -> *mut wire_uint_8_list {
    let ans = wire_uint_8_list {
        ptr: support::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    support::new_leak_box_ptr(ans)
}

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        if self.is_null() {
            None
        } else {
            Some(self.wire2api())
        }
    }
}

impl Wire2Api<String> for *mut wire_uint_8_list {
    fn wire2api(self) -> String {
        let vec: Vec<u8> = self.wire2api();
        String::from_utf8_lossy(&vec).into_owned()
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
    fn wire2api(self) -> Vec<u8> {
        unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}

// Section: impl NewWithNullPtr

pub trait NewWithNullPtr {
    fn new_with_null_ptr() -> Self;
}

impl<T> NewWithNullPtr for *mut T {
    fn new_with_null_ptr() -> Self {
        std::ptr::null_mut()
    }
}

// Section: impl IntoDart

// Section: executor
support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

// Section: sync execution mode utility

#[no_mangle]
pub extern "C" fn free_WireSyncReturnStruct(val: support::WireSyncReturnStruct) {
    unsafe {
        let _ = support::vec_from_leak_ptr(val.ptr, val.len);
    }
}
